version: 2
updates:
  # Configuration for docker
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  # Configuration for github-actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
