name: Build and push Docker image
on: push
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag webdummy:latest
      - name: Tag the Docker image with the short commit hash
        run: docker tag webdummy:latest ghcr.io/daveio/webdummy:$(echo -n ${GITHUB_SHA} | cut -b -7)
      - name: Tag the Docker image with latest
        run: docker tag webdummy:latest ghcr.io/daveio/webdummy:latest
      - name: Log in to GHPR
        run: echo ${GITHUB_TOKEN} | docker login ghcr.io --username daveio --password-stdin
      - name: Push to GHPR (short commit hash)
        run: docker push ghcr.io/daveio/webdummy:$(echo -n ${GITHUB_SHA} | cut -b -7)
      - name: Push to GHPR (latest)
        run: docker push ghcr.io/daveio/webdummy:latest
